export default [
    {
        key: '/home',
        title: '首页',
        icon: 'home',
        road:'../routers/Home'
    },
    {
        key:'/general',
        title:'General',
        icon:'smile',
        list:[
            {
                key:'/button',
                title:'Button',
                icon:'border',
            },
            {
                key:'/icon',
                title:'Icon',
                icon:'italic',
            },
        ],
    },
    {
        key:'/layoutdom',
        title:'LayoutDom',
        icon:'radar-chart',
        list:[
            {
                key:'/grid',
                title:'Grid',
                icon:'project',
            },
            {
                key:'/layouts',
                title:'Layouts',
                icon:'qrcode',
            },
        ],
    },
    {
        key:'/navigation',
        title:'Navigation',
        icon:'heat-map',
        list:[
            {
                key:'/affix',
                title:'Affix',
                icon:'pushpin',
            },
            {
                key:'/breadcrumb',
                title:'Breadcrumb',
                icon:'meh',
            },
            {
                key:'/dropdown',
                title:'Dropdown',
                icon:'arrow-down',
            },
            {
                key:'/menu',
                title:'Menu',
                icon:'menu-fold',
            },
            {
                key:'/pagination',
                title:'Pagination',
                icon:'rocket',
            },
            {
                key:'/steps',
                title:'Steps',
                icon:'block',
            },
        ],
    },
    {
        key:'/data',
        title:'DataEntry',
        icon:'diff',
        list:[
            {
                key:'/autocomplete',
                title:'AutoComplete',
                icon:'sync',
            },
            {
                key:'/cascader',
                title:'Cascader',
                icon:'branches',
            },
            {
                key:'/checkbox',
                title:'Checkbox',
                icon:'sliders',
            },
            {
                key:'/datepicker',
                title:'DatePicker',
                icon:'gateway',
            },
            {
                key:'/form',
                title:'Form',
                icon:'hdd',
            },
            {
                key:'/input',
                title:'Input',
                icon:'italic',
            },
            {
                key:'/inputNumber',
                title:'InputNumber',
                icon:'frown',
            },
            {
                key:'/mention',
                title:'Mention',
                icon:'cluster',
            },
            {
                key:'/rate',
                title:'Rate',
                icon:'star',
            },
            {
                key:'/radio',
                title:'Radio',
                icon:'check-circle',
            },
        ]
    },
]

